from snakemake.utils import Paramspace
import pandas as pd

# declare a dataframe to be a paramspace
paramspace = Paramspace(pd.read_csv('params/params_all.csv'))


rule all:
    input:
        expand(
            'results/{params}.txt',
            params=paramspace.instance_patterns),


rule simulate:
    output:
        f'results/{paramspace.wildcard_pattern}.txt'
    resources:
        mem_mb=5500
    threads: 5
    params:
        # translate the wildcard values into an instance of the param space
        simulation=paramspace.instance
    script:
        'run_simulation.py'

